---
- name: Create scheduled job
  hosts: all
  gather_facts: no

  tasks:
  cron:
    name: "check dirs"
    minute: {{ M_TIME }}
    hour: {{ M_HOUR }}
    job: "ls -alh > /dev/null"
    register: M_TIME
              M_HOUR
