- hosts: all
  gather_facts: false
  become: yes 
  tasks:
  - name: Return service state information as fact data
    service_facts:

  - name: Show the status of etcd service
    debug:
      var: ansible_facts.services['etcd.service']['state']

  - name: Start etcd service if its not running
    service:
      name: etcd.service
      state: started
    when: ansible_facts.services['etcd.service']['state'] != 'running'
