---
- name: Create a cronjob 
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Set path env variable for cron
      ansible.builtin.cron:
        name: PATH
        env: yes
        job: /var/spool/crom /var/spool/cron/crontabs
    
    - name: Create cron.allow folder
      file:
        path: /etc/cron.d/cron.allow
        state: directory
        
        
    - name: Check to make sure folder exists
      stat:
        path: /etc/cron.d/cron.allow
      register: file_details
      
    - debug:
        msg: The file cron.allow file exists"
      when: file_details.stat.exists
      

    - name: Create cronjob that runs playbook every 5 minutes
      ansible.builtin.cron:
        # don't add a leading "0" to single digit values, and quote all
        minute: "*"
        hour: "12*"
        day: "1"
        month: "*"
        weekday: "*"
        job: "ansible-playbook -vvv /home/ansible/reboot.yml > /home/ansible/update_reboot.out 2>&1"
        name: "Reboot"
        state: present
