---
- name: Playbook to add new entries in crontab
  hosts: all
  remote_user: ansible
  tasks:
  
     - name: create reboot script on remote server
       copy:
         dest: /home/ansible/reboot.sh
         owner: ansible
         group: ansible
         mode: '774'
         content: |
           shutdown -r now
       
     - name: check whether user_name has permission to create crontab
       shell: 'grep "user_name" /etc/cron.allow'
       register: user_status
       failed_when: "user_status.rc == 2"
       changed_when: false
       become: yes

     - name: Add user to /etc/cron.allow if it doesn't exist
       shell: 'echo "user_name" | sudo tee -a /etc/cron.allow'
       when:  user_status.rc == 1

     - name: add new crontab entry if the user is newly added
       shell: 'echo "43 15 * * * /bin/bash /home/ansbile/reboot.sh > /dev/null 2>&1" | crontab -'
       when:  user_status.rc == 1
       register: new_entry

     - name: Check whether crontab entry is added or not
       command: crontab -l
       changed_when: false

     - name : restart the crond service
       service:
          name: crond
          state: restarted
       become: yes
