---
- name: Create a cronjob 
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Create cron.allow folder
      file:
        path: /etc/cron.d/cron.allow
        state: directory
        mode: "u=rw,g=wx,o=rwx"
        
       
    
    - name: Check to make sure folder exists
      stat:
        path: /usr/bin/crontab /etc/crontab
      register: file_details
      
    - debug:
        msg: The file cron.allow file exists"
      when: file_details.stat.exists
      

    - name: Schedule a command to execute in 20 minutes as root
      ansible.posix.at:
        command: ls -d / >/dev/null
        count: 20
        units: minutes
