---
- name: Linux Reboot Demo
  hosts: all
  gather_facts: no
  remote_user: ansible
  become: true
 
  tasks:
    - name: Reboot the machine (Wait for 5 min)
      reboot:
        reboot_timeout: 300
