---
- name: Linux Reboot Demo
  hosts: {{ SERVER }}
  gather_facts: no
  remote_user: ansible
  become: true
 
  tasks:
    - name: Reboot the machine (Wait for 60 second)
      reboot:
        reboot_timeout: 60
