---
- name: configure inventory hosts
  hosts: localhost
  gather_facts: no
  
  vars:
    linux_hosts: "{{ survey_hosts.split('\n') }}"  
  
  tasks:
    
  - name: make host group from survey hosts list
    add_host:
      hostname: "{{ item }}"
      groupname: new_group      
    loop: "{{ linux_hosts }}"

- name: switch connecton location of linux openvpn client service
  hosts: new_group,!localhost
  gather_facts: no
  become: true
  
   tasks:
  -  name: Root FS usage
     shell: df -h {{ item }} |awk ' { print $5 } ' |grep -v Use
     register: dfroot

  -  debug:
       msg: "System {{ inventory_hostname }}'s root FS utiliation is {{ dfroot.stdout }}"
